// this code use REST_Client extension

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer /*next indicates the complete token assigned to the user */

{
    "content": "Esto es una nota",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "subscribe to midu",
    "important": true,
    "userId": "s8odhosdfuos9du" //  Put the specific ID of the user
}
