//  Update the content of a especific note indicated by id

PUT  http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Esto es una nota actualizada",
    "important": true
}
